### PR TITLE
Update to 12.0.0

### PR DESCRIPTION
**Pull request by ccordoba12**

### CODE REVIEW

**Comment by ccordoba12** [comment]
@conda-forge-admin, please rerender

**Comment by ccordoba12** [comment]
@jakirkham, @ocefpaf, could you help me with this one? Thanks!

**Comment by ocefpaf** [comment]
@ericdill is a maintainer here, let's wait for his input.

**Comment by ericdill** [comment]
@ccordoba12 thanks for tackling this !

**Comment by ccordoba12** [comment]
No problem, thanks for the quick merge!

**Pull request merged**
